### ISSUE TITLE
Docs for testing operator adapting to state changes such as memcached nodes in a pool being added, removed or replaced

### ISSUE THREAD

**Issue by tima** [geerlingguy/mcrouter-operator#10]
This Operator has a lot a lot of potential to show developers the value of Operators and to show them how to do it using Ansible. To that point, it would be really helpful if you added some docs to the README (perhaps under Testing?) that details how to force changes to the mcrouter pool (memcached pod crashes and is replaced, memcached pool grows or contracts) and to see that the operator has adapted the mcrouter config. The idea being a developer can check if an Operator is detecting the change in state and reconciling it properly. 

There is a lot more scenarios that could be documented to show other things an Operator could facilitate, but I save that request for another day. ;)

**Comment by geerlingguy** [comment]
Good idea! And this goes along with https://github.com/geerlingguy/mcrouter-operator/issues/2, which could then be used to show, live, the status of the operator overall while all these state changes are happening.

**Comment by geerlingguy** [comment]
I have some content already, but I think I may end up doing at least a blog post, if not also a video walkthrough of it, to kind of explore end-to-end how this operator ticks.

It's deceptively simple but is a pretty good starter operator verses something like PostgreSQL or etcd!
