### ISSUE TITLE
Operate cluster-wide, on all namespaces (not just default)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mcrouter-operator#14]
Currently, the operator is set to only monitor the namespace into which it's installed—and by default (in the quick start deployment manifest) it is the `default` namespace.

So... for anyone who uses any other namespace (which should be anyone who uses Kubernetes at all, IMO) for resource isolation, this operator has to be installed in a more annoying / manual fashion.

For my Drupal operator, I already converted it to work across all namespaces (instead of just the one into which it's deployed. And I'd like to do the same for Mcrouter. See [Operator SDK - Operator Scope](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md)

**Comment by geerlingguy** [comment]
Hmm, the docs mention:

> Namespace-scoped operators are preferred because of their flexibility. They enable decoupled upgrades, namespace isolation for failures and monitoring, and differing API definitions.

So do I want to be a purist about this (and follow the docs), or a realist (most people aren't going to run 300 operators for 300 instances of an application, IMO... all the operators I've used (e.g. prometheus, grafana, cert-manager) are cluster-wide.

**Comment by fabianvf** [comment]
We should see if we can support both, obviously installation of RBAC etc would need to be separate but I think it should be possible to allow the user to pick whether they watch the whole cluster or just one namespace
