### ISSUE TITLE
Production readyness 

### ISSUE THREAD

**Issue by Lawouach** [geerlingguy/mcrouter-operator#18]
Hello,

Thank you so much for your work. This is timely for my needs.

You mention that this is not production ready yet. Would you mind shedding a light on what's missing? Just so that I can make a decision to try it :)

Cheers

**Comment by geerlingguy** [comment]
@Lawouach - Mostly, 'support' — this operator is mostly maintained as a demonstration of a simple level 2-ish operator, but I don't make any promises about long-term support or compatibility between releases.

However, you're free to use it as is and/or fork it and maintain it for your own needs too!

**Comment by Lawouach** [comment]
It makes sense. I appreciate the transparency on this one.

I'm thinking I'll give it a spin :)
